apiVersion: v2
name: postgres-cluster
description: A Helm chart for deploying resources for PostgreSQL cluster with CNFC operator
type: application
version: 0.1.0

maintainers:
    - name: Igor Janiak
      email: igor.janiak@wmsdev.pl
      url: https://github.com/SmigorX
