{{- if eq .Values.backup.backupCredentialsSecret.source "vault" }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.backup.backupCredentialsSecret.pullSecretFromVault.name }}
  namespace: {{ .Values.cluster.namespace }}
spec:
  type: kv-v2
  mount: secret
  path: {{ .Values.backup.backupCredentialsSecret.pullSecretFromVault.path }}
  destination:
    name: {{ .Values.backup.backupCredentialsSecret.pullSecretFromVault.name }}
    create: true
---
{{- end }}

{{- if eq .Values.database.recovery.bootstrapS3CredentialsSecret.source "vault" }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.database.recovery.bootstrapS3CredentialsSecret.pullSecretFromVault.name }}
  namespace: {{ .Values.cluster.namespace }}
spec:
  type: kv-v2
  mount: secret
  path: {{ .Values.database.recovery.bootstrapS3CredentialsSecret.pullSecretFromVault.path }}
  destination:
    name: {{ .Values.database.recovery.bootstrapS3CredentialsSecret.pullSecretFromVault.name }}
    create: true
---
{{- end }}

{{- if eq .Values.users.superuserSecret.source "vault" }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.users.superuserSecret.pullSecretFromVault.name }}
  namespace: {{ .Values.cluster.namespace }}
spec:
  type: kv-v2
  mount: secret
  path: {{ .Values.users.superuserSecret.pullSecretFromVault.path }}
  destination:
    name: {{ .Values.users.superuserSecret.pullSecretFromVault.name }}
    create: true
---
{{- end }}

{{- range .Values.users.roles }}
{{- if eq .credentialsSecret.source "vault" }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .credentialsSecret.pullSecretFromVault.name }}
  namespace: {{ $.Values.cluster.namespace }}
spec:
  type: kv-v2
  mount: secret
  path: {{ .credentialsSecret.pullSecretFromVault.path }}
  destination:
    name: {{ .credentialsSecret.pullSecretFromVault.name }}
    create: true
---
{{- end }}
{{- end }}
