name: Release Helm Chart

on:
    push:
        branches:
            - master
        paths:
            - "cluster/**"
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Helm
              uses: azure/setup-helm@v4
              with:
                  version: "latest"

            - name: Log in to GitHub Container Registry
              run: |
                  echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Package and Push Helm Chart
              run: |
                  # 1. Pobieramy dane z właściwego folderu 'cluster'
                  CHART_NAME=$(grep '^name:' cluster/Chart.yaml | awk '{print $2}')
                  CHART_VERSION=$(grep '^version:' cluster/Chart.yaml | awk '{print $2}')

                  echo "Packaging chart $CHART_NAME version $CHART_VERSION"

                  # 2. Pakujemy folder 'cluster'
                  helm package cluster

                  # 3. Wypychamy do GHCR (z małych liter dla pewności)
                  REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
                  helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/${REPO_OWNER}/charts
